---
name: 'Build and Push Container Images'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  latest:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Repo
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          tags: ghcr.io/washu-it-ris/base-openmpi:latest
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title="RIS Intel OneAPI Compiler-Base"
            org.opencontainers.image.description="RIS Managed Intel OneAPI Compiler-Base Container for use with LSF 10.1 Compute1"
            org.opencontainers.image.vendor="ris.wustl.edu"
            org.opencontainers.image.url="https://docs.ris.wustl.edu/doc/compute/recipes/tools/intel-oneapi-tutorial.html"
            org.opencontainers.image.source="https://github.com/WashU-IT-RIS/compiler-base"

  ubuntu22_mofed5-8_oneapi2025:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Repo
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfiles/ubuntu22-mofed5.8-oneapi2025
          tags: ghcr.io/washu-it-ris/base-openmpi:latest
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title="RIS Intel OneAPI Compiler-Base"
            org.opencontainers.image.description="RIS Managed Intel OneAPI Compiler-Base Container for use with LSF 10.1 Compute1"
            org.opencontainers.image.vendor="ris.wustl.edu"
            org.opencontainers.image.url="https://docs.ris.wustl.edu/doc/compute/recipes/tools/intel-oneapi-tutorial.html"
            org.opencontainers.image.source="https://github.com/WashU-IT-RIS/compiler-base"

